services:
  global4ukraine:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/global4ukraine
      - /usr/src/global4ukraine/node_modules
      - /usr/src/global4ukraine/.next
